CREATE TABLE otp_v1 (
    id uuid NOT NULL PRIMARY KEY,
    otp VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    used BOOLEAN NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX otp_v1_email_ref_idx ON otp_v1 (email);
