version: '3'

services:
  postgresregister:
    hostname: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=none"]
    networks:
      - register-net
  kafkaregister:
    hostname: kafka
    image: confluentinc/cp-kafka:7.3.1
    logging:
      driver: none
    depends_on:
      - zookeeperregister
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - register-net
  zookeeperregister:
    image: confluentinc/cp-zookeeper:7.3.1
    hostname: zookeeper
    logging:
      driver: none
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - register-net
  redisregister:
    image: redis:7.0.11-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - register-net
  mediaregister:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamdigihot/hm-grunndata-media:23.223.111226
    platform: linux/amd64
    hostname: media
    depends_on:
      - postgresregister
    ports:
      - "8081:8080"
    networks:
      - register-net
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_JDBC_URL: "jdbc:postgresql://postgres:5432/media"
      MICRONAUT_ENVIRONMENTS: local
      RAPIDSANDRIVERS_ENABLED: true
      KAFKA_BROKERS: "kafka:9092"
      MEDIA_STORAGE_CDNURL: http://localhost:8081/local
    volumes:
      - /tmp/teamdigihot/grunndata/media/v1:/app/teamdigihot/grunndata/media/v1
  mediaproxyregister:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamdigihot/hm-grunndata-media-proxy:23.233.175541
    platform: linux/amd64
    hostname: mediaproxy
    depends_on:
      - redisregister
      - mediaregister
    ports:
      - "8082:8080"
    networks:
      - register-net
    environment:
      MEDIA_STORAGE_CDNURL: "http://media:8080/local"
      REDIS_HOST: "redis"
  register:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamdigihot/hm-grunndata-register:23.278.141105
    platform: linux/amd64
    hostname: register
    depends_on:
      - postgresregister
    ports:
      - "8080:8080"
    networks:
      - register-net
    environment:
      MEDIA_UPLOAD_URL: "http://media:8080/api/v1/upload/media/register"
      GRUNNDATA_DB_URL: "http://localhost:8080/"
      COOKIE_DOMAIN: localhost
      DB_DRIVER: org.postgresql.Driver
      DB_JDBC_URL: "jdbc:postgresql://postgres:5432/register"
      RAPIDSANDRIVERS_ENABLED: true
      KAFKA_BROKERS: "kafka:9092"
      MICRONAUT_SERVER_CORS_ENABLED: true
networks:
  register-net:
