apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-register
  namespace: teamdigihot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /admreg/internal/isAlive
    initialDelay: 20
  readiness:
    path: /admreg/internal/isReady
    initialDelay: 20
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /admreg/internal/prometheus
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  envFrom:
    - secret: hm-grunndata-register
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: DB_JDBC_URL
      value: "jdbc:postgresql://${DB_HOST}:5432/register"
    - name: RAPIDSANDRIVERS_ENABLED
      value: "{{ rapidsandrivers_enabled }}"
    - name: MEDIA_UPLOAD_URL
      value: "{{ media_upload_url }}"
    - name: COOKIE_DOMAIN
      value: "{{ cookie_domain }}"
    - name: MEDIA_UPLOAD_URL
      value: "http://hm-grunndata-media"
    - name: SWAGGER_ENABLED
      value: "{{ swagger_enabled }}"
    - name: SCHEDULERS_ENABLED
      value: "{{ schedulers_enabled }}"
    - name: IMPORT_AUTOAPPROVE
      value: "{{ import_autoapprove }}"
    - name: SERVER_PORT
      value: "8080"
    - name: JAVA_OPTS
      value: "{{ java_opts }}"
  gcp:
    sqlInstances:
      - name: hm-grunndata-register
        type: POSTGRES_14
        tier: {{ disk_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ disk_size }}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: register
            envVarPrefix: DB
        cascadingDelete: false
    bigQueryDatasets:
      - name: hm-grunndata-register
        permission: READWRITE
  kafka:
    pool: {{ kafka_cluster }}
  leaderElection: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-media
        - application: hm-grunndata-db
      external:
        - host: login.microsoftonline.com
        - host: graph.microsoft.com
        - host: navikt.github.io
