ALTER TABLE product_reg_v1 ALTER COLUMN title TYPE VARCHAR(1024);
ALTER TABLE product_reg_v1 ALTER COLUMN article_name TYPE VARCHAR(1024);
ALTER TABLE series_reg_v1 ALTER COLUMN title TYPE VARCHAR(1024);