micronaut:
  application:
    name: hm-grunndata-register
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  security:
    redirect:
      enabled: false
    endpoints:
      login:
        enabled: true
        path: "/login"
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SECRET:MustBeAVeryLongSecretAndUsedThisForTestOnly}
              jws-algorithm: HS256
        cookie:
          max-age: 3600
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///gdb?TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:register}
    password: ${DB_PASSWORD:register}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db
