/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admreg/admin/api/v1/agreement/registrations": {
    get: operations["findAgreements"];
    post: operations["createAgreement"];
  };
  "/admreg/admin/api/v1/agreement/registrations/draft/from/{id}/reference/{reference}": {
    post: operations["createAgreementFromAnother"];
  };
  "/admreg/admin/api/v1/agreement/registrations/draft/reference/{reference}": {
    post: operations["draftAgreement"];
  };
  "/admreg/admin/api/v1/agreement/registrations/{id}": {
    get: operations["getAgreementById"];
    put: operations["updateAgreement"];
  };
  "/admreg/admin/api/v1/import/token/{supplierId}": {
    post: operations["createSupplierToken"];
  };
  "/admreg/admin/api/v1/media/agreement/files/{oid}": {
    post: operations["uploadAgreementFiles"];
  };
  "/admreg/admin/api/v1/media/product/files/{oid}": {
    post: operations["uploadProductFiles"];
  };
  "/admreg/admin/api/v1/media/{oid}": {
    get: operations["getMediaList"];
  };
  "/admreg/admin/api/v1/media/{oid}/{uri}": {
    delete: operations["deleteFile"];
  };
  "/admreg/admin/api/v1/product/registrations": {
    get: operations["findProducts"];
    post: operations["createProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/approve/{id}": {
    put: operations["approveProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/draft/supplier/{supplierId}": {
    post: operations["draftProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/draft/variant/{id}/reference/{supplierRef}": {
    post: operations["createProductVariant"];
  };
  "/admreg/admin/api/v1/product/registrations/series/group?": {
    get: operations["findSeriesGroup"];
  };
  "/admreg/admin/api/v1/product/registrations/series/{seriesId}": {
    get: operations["findBySeriesIdAndSupplierId"];
  };
  "/admreg/admin/api/v1/product/registrations/{id}": {
    get: operations["getProductById"];
    put: operations["updateProduct"];
    delete: operations["deleteProduct"];
  };
  "/admreg/admin/api/v1/supplier/registrations": {
    get: operations["findSuppliers"];
    post: operations["createSupplier"];
  };
  "/admreg/admin/api/v1/supplier/registrations/{id}": {
    get: operations["getById"];
    put: operations["updateSupplier"];
    delete: operations["deactivateSupplier"];
  };
  "/admreg/admin/api/v1/users": {
    get: operations["getUsers"];
    post: operations["createUser"];
  };
  "/admreg/admin/api/v1/users/email/{email}": {
    get: operations["getUserByEmail"];
  };
  "/admreg/admin/api/v1/users/supplierId/{supplierId}": {
    get: operations["getUsersBySupplierId"];
  };
  "/admreg/admin/api/v1/users/{id}": {
    get: operations["getUser"];
    put: operations["updateUser"];
    delete: operations["deleteUser"];
  };
  "/admreg/api/v1/isocategories": {
    get: operations["getAllCategories"];
  };
  "/admreg/api/v1/isocategories/{isocode}": {
    get: operations["getCategoryByIsocode"];
  };
  "/admreg/api/v1/techlabels": {
    get: operations["fetchTechLabels"];
  };
  "/admreg/api/v1/techlabels/name/{name}": {
    get: operations["fetchTechLabelsByName"];
  };
  "/admreg/api/v1/techlabels/{isocode}": {
    get: operations["fetchTechLabelsByIsocode"];
  };
  "/admreg/keys": {
    get: operations["keys"];
  };
  "/admreg/loggedInUser": {
    get: operations["getLoggedInUser"];
  };
  "/admreg/login": {
    post: operations["login"];
  };
  "/admreg/logout": {
    get: operations["indexGet"];
    post: operations["index"];
  };
  "/admreg/vendor/api/v1/agreement/registrations": {
    get: operations["findAgreements_1"];
  };
  "/admreg/vendor/api/v1/media/product/files/{oid}": {
    post: operations["uploadFiles"];
  };
  "/admreg/vendor/api/v1/media/{oid}": {
    get: operations["getMediaList_1"];
  };
  "/admreg/vendor/api/v1/media/{oid}/{uri}": {
    delete: operations["deleteFile_1"];
  };
  "/admreg/vendor/api/v1/product/registrations": {
    get: operations["findProducts_1"];
    post: operations["createProduct_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/draft": {
    post: operations["draftProduct_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/draft/variant/{id}/reference/{supplierRef}": {
    post: operations["createProductVariant_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/series/group?": {
    get: operations["findSeriesGroup_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/series/{seriesId}": {
    get: operations["findBySeriesIdAndSupplierId_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/{id}": {
    get: operations["getProductById_1"];
    put: operations["updateProduct_1"];
    delete: operations["deleteProduct_1"];
  };
  "/admreg/vendor/api/v1/series": {
    get: operations["getSeries"];
  };
  "/admreg/vendor/api/v1/supplier/registrations": {
    get: operations["getById_1"];
    put: operations["updateSupplier_1"];
  };
  "/admreg/vendor/api/v1/users": {
    get: operations["getUsers_1"];
    put: operations["updateUser_1"];
  };
  "/admreg/vendor/api/v1/users/password": {
    put: operations["changePassword"];
  };
  "/admreg/vendor/api/v1/users/{userId}": {
    get: operations["getUserId"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AdminInfo: {
      approvedBy?: string | null;
      note?: string | null;
      /** Format: date-time */
      approved?: string | null;
    };
    /** @enum {string} */
    AdminStatus: "PENDING" | "APPROVED" | "REJECTED";
    AgreementAttachment: {
      title?: string | null;
      media: components["schemas"]["MediaInfo"][];
      description?: string | null;
    };
    AgreementData: {
      resume?: string | null;
      text?: string | null;
      identifier: string;
      attachments: components["schemas"]["AgreementAttachment"][];
      posts: components["schemas"]["AgreementPost"][];
      isoCategory: string[];
    };
    AgreementInfo: {
      /** Format: uuid */
      id: string;
      identifier?: string | null;
      title?: string | null;
      /** Format: int32 */
      rank: number;
      /** Format: int32 */
      postNr: number;
      postIdentifier?: string | null;
      postTitle?: string | null;
      reference: string;
      /** Format: date-time */
      expired: string;
    };
    AgreementPost: {
      identifier: string;
      /** Format: int32 */
      nr: number;
      title: string;
      description: string;
      /** Format: date-time */
      created: string;
    };
    AgreementRegistrationDTO: {
      /** Format: uuid */
      id: string;
      draftStatus: components["schemas"]["DraftStatus"];
      agreementStatus: components["schemas"]["AgreementStatus"];
      title: string;
      reference: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published: string;
      /** Format: date-time */
      expired: string;
      createdByUser: string;
      updatedByUser: string;
      createdBy: string;
      updatedBy: string;
      agreementData: components["schemas"]["AgreementData"];
      /** Format: int64 */
      version?: number | null;
    };
    /** @enum {string} */
    AgreementStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    Attributes: {
      manufacturer?: string | null;
      compatibleWidth?: components["schemas"]["CompatibleWith"] | null;
      keywords?: string[] | null;
      series?: string | null;
      shortdescription?: string | null;
      text?: string | null;
      url?: string | null;
      bestillingsordning?: boolean | null;
      tenderId?: string | null;
      hasTender?: boolean | null;
    };
    Authentication: components["schemas"]["Principal"] & {
      attributes: {
        [key: string]: unknown;
      };
      roles: string[];
    };
    ChangePasswordDTO: {
      oldPassword: string;
      newPassword: string;
    };
    CompatibleWith: {
      seriesIds: string[];
    };
    /** @enum {string} */
    DraftStatus: "DRAFT" | "DONE";
    IsoCategoryDTO: {
      isoCode: string;
      isoTitle: string;
      isoText: string;
      isoTranslations?: components["schemas"]["IsoTranslationsDTO"] | null;
      /** Format: int32 */
      isoLevel: number;
      isActive: boolean;
      showTech: boolean;
      allowMulti: boolean;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    IsoTranslationsDTO: {
      titleEn?: string | null;
      textEn?: string | null;
    };
    MediaDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      oid: string;
      uri: string;
      sourceUri: string;
      type: string;
      /** Format: int64 */
      size: number;
      md5: string;
      status: string;
      source: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    MediaInfo: {
      sourceUri: string;
      uri: string;
      /** Format: int32 */
      priority: number;
      type: components["schemas"]["MediaType"];
      text?: string | null;
      source: components["schemas"]["MediaSourceType"];
      /** Format: date-time */
      updated: string;
    };
    /** @enum {string} */
    MediaSourceType: "HMDB" | "REGISTER" | "EXTERNALURL" | "IMPORT" | "UNKNOWN";
    /** @enum {string} */
    MediaType: "PDF" | "IMAGE" | "VIDEO" | "XLS" | "OTHER";
    OpenApiPageable: {
      /**
       * Format: int32
       * @description page number
       * @example 0
       */
      number: number;
      /**
       * Format: int32
       * @description Page size
       * @example 100
       */
      size: number;
      /**
       * @description Sort
       * @example updated,desc
       */
      sort: string;
    };
    Page_AgreementRegistrationDTO_: components["schemas"]["Slice_AgreementRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_ProductRegistrationDTO_: components["schemas"]["Slice_ProductRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_SeriesRegistrationDTO_: components["schemas"]["Slice_SeriesRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_SupplierRegistrationDTO_: components["schemas"]["Slice_SupplierRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_UserDTO_: components["schemas"]["Slice_UserDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Principal: {
      name?: string;
    };
    ProductData: {
      attributes: components["schemas"]["Attributes"];
      accessory: boolean;
      sparePart: boolean;
      techData: components["schemas"]["TechData"][];
      media: components["schemas"]["MediaInfo"][];
      /** @deprecated */
      agreementInfo?: components["schemas"]["AgreementInfo"] | null;
      agreements: components["schemas"]["AgreementInfo"][];
    };
    ProductRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      supplierId: string;
      supplierRef: string;
      hmsArtNr?: string | null;
      seriesId: string;
      isoCategory: string;
      title: string;
      articleName: string;
      draftStatus: components["schemas"]["DraftStatus"];
      adminStatus: components["schemas"]["AdminStatus"];
      registrationStatus: components["schemas"]["RegistrationStatus"];
      message?: string | null;
      adminInfo?: components["schemas"]["AdminInfo"] | null;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published?: string | null;
      /** Format: date-time */
      expired?: string | null;
      updatedByUser: string;
      createdByUser: string;
      createdBy: string;
      updatedBy: string;
      createdByAdmin: boolean;
      productData: components["schemas"]["ProductData"];
      /** Format: int64 */
      version?: number | null;
    };
    /** @enum {string} */
    RegistrationStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    SeriesGroupDTO: {
      title: string;
      seriesId: string;
      /** Format: int64 */
      count: number;
    };
    SeriesRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      supplierId: string;
      identifier: string;
      title: string;
      text: string;
      isoCategory: string;
      draftStatus: components["schemas"]["DraftStatus"];
      status: components["schemas"]["SeriesStatus"];
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      expired: string;
      createdBy: string;
      updatedBy: string;
      updatedByUser: string;
      createdByUser: string;
      createdByAdmin: boolean;
      /** Format: int64 */
      version?: number | null;
    };
    /** @enum {string} */
    SeriesStatus: "ACTIVE" | "INACTIVE" | "PENDING" | "REJECTED";
    Slice_AgreementRegistrationDTO_: {
      content: components["schemas"]["AgreementRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_ProductRegistrationDTO_: {
      content: components["schemas"]["ProductRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_SeriesRegistrationDTO_: {
      content: components["schemas"]["SeriesRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_SupplierRegistrationDTO_: {
      content: components["schemas"]["SupplierRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_UserDTO_: {
      content: components["schemas"]["UserDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    SupplierData: {
      address?: string | null;
      postNr?: string | null;
      postLocation?: string | null;
      countryCode?: string | null;
      email?: string | null;
      phone?: string | null;
      homepage?: string | null;
    };
    SupplierRegistrationDTO: {
      /** Format: uuid */
      id: string;
      status: components["schemas"]["SupplierStatus"];
      draftStatus: components["schemas"]["DraftStatus"];
      name: string;
      supplierData: components["schemas"]["SupplierData"];
      identifier: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      createdBy: string;
      updatedBy: string;
      updatedByUser: string;
      createdByUser: string;
    };
    /** @enum {string} */
    SupplierStatus: "INACTIVE" | "ACTIVE";
    TechData: {
      key: string;
      value: string;
      unit: string;
    };
    TechLabelDTO: {
      /** Format: uuid */
      id: string;
      identifier: string;
      label: string;
      guide: string;
      isocode: string;
      type: string;
      unit?: string | null;
      createdBy: string;
      updatedBy: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    UserDTO: {
      /** Format: uuid */
      id: string;
      name: string;
      email: string;
      roles: string[];
      attributes: {
        [key: string]: string;
      };
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    UserRegistrationDTO: {
      /** Format: uuid */
      id: string;
      name: string;
      email: string;
      password: string;
      roles: string[];
      attributes: {
        [key: string]: string;
      };
    };
    UsernamePasswordCredentials: {
      username: string | null;
      password: string | null;
      identity?: string | null;
      secret?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  findAgreements: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findAgreements 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_AgreementRegistrationDTO_"];
        };
      };
    };
  };
  createAgreement: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgreementRegistrationDTO"];
      };
    };
    responses: {
      /** @description createAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  createAgreementFromAnother: {
    parameters: {
      path: {
        id: string;
        reference: string;
      };
    };
    responses: {
      /** @description createAgreementFromAnother 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  draftAgreement: {
    parameters: {
      path: {
        reference: string;
      };
    };
    responses: {
      /** @description draftAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  getAgreementById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getAgreementById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  updateAgreement: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgreementRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  createSupplierToken: {
    parameters: {
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description createSupplierToken 200 response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  uploadAgreementFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadAgreementFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  uploadProductFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadProductFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  getMediaList: {
    parameters: {
      path: {
        oid: string;
      };
    };
    responses: {
      /** @description getMediaList 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  deleteFile: {
    parameters: {
      path: {
        oid: string;
        uri: string;
      };
    };
    responses: {
      /** @description deleteFile 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"];
        };
      };
    };
  };
  findProducts: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findProducts 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ProductRegistrationDTO_"];
        };
      };
    };
  };
  createProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description createProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  approveProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description approveProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProduct: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description draftProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createProductVariant: {
    parameters: {
      path: {
        id: string;
        supplierRef: string;
      };
    };
    responses: {
      /** @description createProductVariant 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findSeriesGroup: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSeriesGroup 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SeriesGroupDTO"][];
        };
      };
    };
  };
  findBySeriesIdAndSupplierId: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    responses: {
      /** @description findBySeriesIdAndSupplierId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  getProductById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  deleteProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findSuppliers: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSuppliers 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_SupplierRegistrationDTO_"];
        };
      };
    };
  };
  createSupplier: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description createSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  updateSupplier: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  deactivateSupplier: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deactivateSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getUsers: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description getUsers 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_UserDTO_"];
        };
      };
    };
  };
  createUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegistrationDTO"];
      };
    };
    responses: {
      /** @description createUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  getUserByEmail: {
    parameters: {
      path: {
        email: string;
      };
    };
    responses: {
      /** @description getUserByEmail 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  getUsersBySupplierId: {
    parameters: {
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description getUsersBySupplierId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"][];
        };
      };
    };
  };
  getUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDTO"];
      };
    };
    responses: {
      /** @description updateUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteUser 200 response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  getAllCategories: {
    responses: {
      /** @description getAllCategories 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryDTO"][];
        };
      };
    };
  };
  getCategoryByIsocode: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    responses: {
      /** @description getCategoryByIsocode 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryDTO"];
        };
      };
    };
  };
  fetchTechLabels: {
    responses: {
      /** @description fetchTechLabels 200 response */
      200: {
        content: {
          "application/json": {
            [key: string]: components["schemas"]["TechLabelDTO"][];
          };
        };
      };
    };
  };
  fetchTechLabelsByName: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description fetchTechLabelsByName 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelDTO"][];
        };
      };
    };
  };
  fetchTechLabelsByIsocode: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    responses: {
      /** @description fetchTechLabelsByIsocode 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelDTO"][];
        };
      };
    };
  };
  keys: {
    responses: {
      /** @description keys 200 response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getLoggedInUser: {
    responses: {
      /** @description getLoggedInUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Authentication"];
        };
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["UsernamePasswordCredentials"];
        "application/json": components["schemas"]["UsernamePasswordCredentials"];
      };
    };
    responses: {
      /** @description login 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  indexGet: {
    responses: {
      /** @description indexGet 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  index: {
    responses: {
      /** @description index 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  findAgreements_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findAgreements_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_AgreementRegistrationDTO_"];
        };
      };
    };
  };
  uploadFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  getMediaList_1: {
    parameters: {
      path: {
        oid: string;
      };
    };
    responses: {
      /** @description getMediaList_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  deleteFile_1: {
    parameters: {
      path: {
        oid: string;
        uri: string;
      };
    };
    responses: {
      /** @description deleteFile_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"];
        };
      };
    };
  };
  findProducts_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findProducts_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ProductRegistrationDTO_"];
        };
      };
    };
  };
  createProduct_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description createProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProduct_1: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
    };
    responses: {
      /** @description draftProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createProductVariant_1: {
    parameters: {
      path: {
        id: string;
        supplierRef: string;
      };
    };
    responses: {
      /** @description createProductVariant_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findSeriesGroup_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSeriesGroup_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SeriesGroupDTO"][];
        };
      };
    };
  };
  findBySeriesIdAndSupplierId_1: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    responses: {
      /** @description findBySeriesIdAndSupplierId_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  getProductById_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductById_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  updateProduct_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  deleteProduct_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  getSeries: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description getSeries 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_SeriesRegistrationDTO_"];
        };
      };
    };
  };
  getById_1: {
    responses: {
      /** @description getById_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  updateSupplier_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateSupplier_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getUsers_1: {
    responses: {
      /** @description getUsers_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"][];
        };
      };
    };
  };
  updateUser_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDTO"];
      };
    };
    responses: {
      /** @description updateUser_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  changePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDTO"];
      };
    };
    responses: {
      /** @description changePassword 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getUserId: {
    parameters: {
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description getUserId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
}
